version: "3"
services:
  dbdb:
    image: mariadb:10.9.8
    networks:
      - ums-back-office
    environment:
      MARIADB_DATABASE: ums
      MARIADB_USER: dev
      MARIADB_PASSWORD: devpass
      MARIADB_ROOT_PASSWORD: devpass
    volumes:
      - db:/var/lib/mysql
  frontend:
    image: frontend
    build: ./frontend
    networks:
      - ums-user-facing
  backend:
    image: backend
    build: ./backend
    depends_on:
      - dbdb
    environment:
      UMS_DB_NAME: ums
      UMS_DB_USERNAME: dev
      UMS_DB_PASSWORD: devpass
      UMS_DB_IP: dbdb
    networks:
      - ums-user-facing
      - ums-back-office
  proxy:
    image: nginx:1.21
    ports:
      - "7887:80"
    depends_on:
      - frontend
      - backend
    networks:
      - ums-user-facing
    volumes:
      - "./proxy/default.conf:/etc/nginx/conf.d/default.conf"
volumes:
  db:
    driver: local
networks:
  ums-user-facing:
  ums-back-office:
